
server {
    listen 80;
    server_name vihangatheekshana.me www.vihangatheekshana.me;
    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl;
    server_name vihangatheekshana.me www.vihangatheekshana.me;

    # SSL Certificates
    ssl_certificate /etc/letsencrypt/live/vihangatheekshana.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vihangatheekshana.me/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8080/;
    }
    location /uploads/ {
        proxy_pass http://backend:8080/uploads/;
    }
}